In [1]:
import pandas as pd
df=pd.read_csv("student_messy.csv")

In [2]:
df["department"] = df["department"].str.strip()
df["department"] = df["department"].str.title()

In [3]:
dept_avg = df.groupby("department")["marks"].mean().reset_index(name="avg_marks")
dept_avg

         department  avg_marks
0  Computer Science       86.0
1       Electronics       72.0
2        Mechanical       58.0

In [4]:
merged = df.merge(dept_avg, on="department")
merged

   student_id           name        department  marks  semester  avg_marks
0         101  Ananya Sharma  Computer Science   88.0         4       86.0
1         102  Vikram Singh   Computer Science   72.0         4       86.0
2         103      Zara Khan       Electronics    NaN         4       72.0
3         104    Rohan Gupta       Electronics   65.0         3       72.0
4         105    Priya Patel  Computer Science   91.0         4       86.0
5         101  Ananya Sharma  Computer Science   88.0         4       86.0
6         107    Karan Mehta        Mechanical   58.0         3       58.0
7         108    Sneha Reddy       Electronics   79.0         3       72.0
8         109     Arjun Nair        Mechanical    NaN         3       58.0
9         110    Priya Patel  Computer Science   91.0         4       86.0

In [5]:
result = merged[
    ((merged["department"] == "Computer Science") |
     (merged["department"] == "Mechanical")) &
    (merged["marks"] < merged["avg_marks"])
]

result

   student_id           name        department  marks  semester  avg_marks
1         102  Vikram Singh   Computer Science   72.0         4       86.0