In [2]:
import numpy as np
import pandas as pd
from io import StringIO

In [3]:
from io import StringIO

data = """order_id,customer,city,amount,status
5001,Rahul Verma,Mumbai,2500,Delivered
5002,Fatima Sheikh ,mumbai,1800,Delivered
5003,Suresh Iyer,Bangalore,,Delivered
5004,Meena Joshi,BANGALORE,3200,Cancelled
5001,Rahul Verma,Mumbai,2500,Delivered
5006,Aakash Bose,Pune,4100,Delivered
5007,Divya Nair,Chennai,,Pending
"""

df = pd.read_csv(StringIO(data))
df

   order_id        customer       city  amount     status
0      5001     Rahul Verma     Mumbai  2500.0  Delivered
1      5002  Fatima Sheikh      mumbai  1800.0  Delivered
2      5003     Suresh Iyer  Bangalore     NaN  Delivered
3      5004     Meena Joshi  BANGALORE  3200.0  Cancelled
4      5001     Rahul Verma     Mumbai  2500.0  Delivered
5      5006     Aakash Bose       Pune  4100.0  Delivered
6      5007      Divya Nair    Chennai     NaN    Pending

In [4]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
dtype: bool

In [5]:
df =df.drop_duplicates()
df

   order_id        customer       city  amount     status
0      5001     Rahul Verma     Mumbai  2500.0  Delivered
1      5002  Fatima Sheikh      mumbai  1800.0  Delivered
2      5003     Suresh Iyer  Bangalore     NaN  Delivered
3      5004     Meena Joshi  BANGALORE  3200.0  Cancelled
5      5006     Aakash Bose       Pune  4100.0  Delivered
6      5007      Divya Nair    Chennai     NaN    Pending

In [6]:
df['customer']=df['customer'].str.strip()
df['city']=df['city'].str.strip()
df

   order_id       customer       city  amount     status
0      5001    Rahul Verma     Mumbai  2500.0  Delivered
1      5002  Fatima Sheikh     mumbai  1800.0  Delivered
2      5003    Suresh Iyer  Bangalore     NaN  Delivered
3      5004    Meena Joshi  BANGALORE  3200.0  Cancelled
5      5006    Aakash Bose       Pune  4100.0  Delivered
6      5007     Divya Nair    Chennai     NaN    Pending

In [7]:
df['city']=df['city'].str.title()
df

   order_id       customer       city  amount     status
0      5001    Rahul Verma     Mumbai  2500.0  Delivered
1      5002  Fatima Sheikh     Mumbai  1800.0  Delivered
2      5003    Suresh Iyer  Bangalore     NaN  Delivered
3      5004    Meena Joshi  Bangalore  3200.0  Cancelled
5      5006    Aakash Bose       Pune  4100.0  Delivered
6      5007     Divya Nair    Chennai     NaN    Pending

In [11]:
city_avg=df.groupby('city')['amount'].transform('mean')
df['amount']=df['amount'].fillna(city_avg)
df

   order_id       customer       city  amount     status
0      5001    Rahul Verma     Mumbai  2500.0  Delivered
1      5002  Fatima Sheikh     Mumbai  1800.0  Delivered
2      5003    Suresh Iyer  Bangalore  3200.0  Delivered
3      5004    Meena Joshi  Bangalore  3200.0  Cancelled
5      5006    Aakash Bose       Pune  4100.0  Delivered
6      5007     Divya Nair    Chennai     NaN    Pending