In [1]:
import pandas as pd
df= pd.read_csv("student_messy.csv")
df

   student_id           name        department  marks  semester
0         101  Ananya Sharma  Computer Science   88.0         4
1         102  Vikram Singh   computer science   72.0         4
2         103      Zara Khan       Electronics    NaN         4
3         104    Rohan Gupta       ELECTRONICS   65.0         3
4         105    Priya Patel  Computer Science   91.0         4
5         101  Ananya Sharma  Computer Science   88.0         4
6         107    Karan Mehta        Mechanical   58.0         3
7         108    Sneha Reddy       electronics   79.0         3
8         109     Arjun Nair        Mechanical    NaN         3
9         110    Priya Patel  Computer Science   91.0         4

In [6]:
df = df.drop_duplicates()

df["name"] = df["name"].str.strip()
df["department"] = df["department"].str.strip()
df["department"] = df["department"].str.title()

dept_avg = df.groupby("department")["marks"].transform("mean")
df["marks"] = df["marks"].fillna(dept_avg)

df

   student_id           name        department  marks  semester
0         101  Ananya Sharma  Computer Science   88.0         4
1         102   Vikram Singh  Computer Science   72.0         4
2         103      Zara Khan       Electronics   72.0         4
3         104    Rohan Gupta       Electronics   65.0         3
4         105    Priya Patel  Computer Science   91.0         4
6         107    Karan Mehta        Mechanical   58.0         3
7         108    Sneha Reddy       Electronics   79.0         3
8         109     Arjun Nair        Mechanical   58.0         3
9         110    Priya Patel  Computer Science   91.0         4