In [7]:
import pandas as pd
df=pd.read_csv("student_messy.csv")
departments=pd.read_csv("departments.csv")
departments

         department building head_of_department
0  Computer Science  Block A           Dr. Nair
1       Electronics  Block B           Dr. Iyer
2        Mechanical  Block C            Dr. Rao

In [10]:
df["department"] = df["department"].str.strip()
df["department"] = df["department"].str.title()

In [11]:
left_merge = df.merge(departments, on="department", how="left")
left_merge

,student_id,name,department,marks,semester,building,head_of_department
0,101,Ananya Sharma,Computer Science,88.0,4,Block A,Dr. Nair
1,102,Vikram Singh,Computer Science,72.0,4,Block A,Dr. Nair
2,103,Zara Khan,Electronics,NaN,4,Block B,Dr. Iyer
3,104,Rohan Gupta,Electronics,65.0,3,Block B,Dr. Iyer
4,105,Priya Patel,Computer Science,91.0,4,Block A,Dr. Nair
5,101,Ananya Sharma,Computer Science,88.0,4,Block A,Dr. Nair
6,107,Karan Mehta,Mechanical,58.0,3,Block C,Dr. Rao
7,108,Sneha Reddy,Electronics,79.0,3,Block B,Dr. Iyer
8,109,Arjun Nair,Mechanical,NaN,3,Block C,Dr. Rao
9,110,Priya Patel,Computer Science,91.0,4,Block A,Dr. Nair

In [12]:
inner_merge = df.merge(departments, on="department", how="inner")
inner_merge

,student_id,name,department,marks,semester,building,head_of_department
0,101,Ananya Sharma,Computer Science,88.0,4,Block A,Dr. Nair
1,102,Vikram Singh,Computer Science,72.0,4,Block A,Dr. Nair
2,103,Zara Khan,Electronics,NaN,4,Block B,Dr. Iyer
3,104,Rohan Gupta,Electronics,65.0,3,Block B,Dr. Iyer
4,105,Priya Patel,Computer Science,91.0,4,Block A,Dr. Nair
5,101,Ananya Sharma,Computer Science,88.0,4,Block A,Dr. Nair
6,107,Karan Mehta,Mechanical,58.0,3,Block C,Dr. Rao
7,108,Sneha Reddy,Electronics,79.0,3,Block B,Dr. Iyer
8,109,Arjun Nair,Mechanical,NaN,3,Block C,Dr. Rao
9,110,Priya Patel,Computer Science,91.0,4,Block A,Dr. Nair

In [13]:
print("Left Merge Rows:", len(left_merge))
print("Inner Merge Rows:", len(inner_merge))

Left Merge Rows: 10
Inner Merge Rows: 10